
spring:
  profiles:
    active: food   #选择文档

--- #文档1开始
spring:
  profiles: food

  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
#    通过配置方式加载监听器
context:
  listener:
    classes: com.cml.listener.CustomListener
##使用注解 则不需要配置xml
##  mybatis
#mybatis:
##  需要xml配置文件
##  config-location: classpath:mybatis-config.xml
##不需要xml配置文件
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.cml.domain

server:
  port: 8090

#bean
user:
  id: 1
  username: 曹梦龙1
  password: 123456

#bean
food:
  hanbao: 汉堡1
  shutiao: 薯条1

#  sql日志打印
logging:
  level:
    com.cml.mapper: DEBUG

---
#文档2开始 freemarker模板
spring:
  profiles: freemarker
  mvc:
    view:
      #文件位置 不能更改
      prefix: /templates/
      #文件后缀
      suffix: .ftl
server:
  port: 8080
